#' guard function for unresolved Shiny input fields
#'
#' Calling reactive functions before all required input fields have been resolved can cause warning messages
#' in the log and the screen. This function checks to see if all the required inputs are defined. If so,
#' a value of true is returned other-wise false. The names of the required inputs are given as a space
#' deliminated string and converted to Shiny input keys by a user supplied function ns generated by Shiny's
#' function \[Shiny]{NS}. This function is inspired on guard in Apple's Swift language.
#'
#' @param input a shiny input object
#' @param ns a function generated by Shiny's \[shiny]{NS}
#' @param names a spaced deliminated string containing the required fields
#'
#' @return a logical scalar
#' @export
#'
#' @examples
#' # simulate a Shiny function scenario
#' ns=NS("demo")
#' input=list("demo-a"=1:3,
#'            "demo-b"=NULL,
#'            "demo-c"=3:5)
#'
#' guard(input,ns,"a b c")
#' guard(input,ns,"a c")

guard=function(input,ns,names){

  OK=T

  for (name in strsplit(names,"\\s+")[[1]]){

    if (is.null(input[[ns(name)]])){
      OK=F
    }
  }

  OK
}

library(shiny)


