#' runs one or more tests on a GO object
#'
#' A wrapper to pass multiple tests to \link[topGO]{runTest}.
#'
#' @param goObj a defined GO generated by \link{makeGOobject}
#' @param tests a character vector of one or more tests. See \link[topGO]{whichTests} for details
#' @param algorithm a character string specifying the algorithm to be used. See \link[topGO]{whichWhich} for details
#' @param ... additional options passed to runTest
#'
#' @return a list of GO results for one or more tests. Entries are named by tests.
#' @export
#'
#' @examples
#' #basic example
#'
#' P2a=P2[[1]]
#' P2a
#'
#' head(P2a$data)
#'
#' goObject=makeGOobject(P2a)
#' runObj=runGOtests(goObject,c("ks","fisher"))
#'
#' GenTable(goObject,runObj[[1]])
#' GenTable(goObject,a=runObj[[1]],b=runObj[[2]])
#'
#' # alternative front wrapper
#' tabulateGoResults(goObject,runObj)

runGOtests=function(goObj,
                    tests="ks",
                    algorithm="classic",
                    ...){

  if (all(tests %in% whichTests())){

    out=list()
    for (test in tests){
      incProgress(amount = 0.1, message = NULL, detail = sprintf("running %s",test))
      out[[test]]=results=runTest(goObj,
                                  algorithm=algorithm,
                                  statistic=test
                                  ,...)
    }

    out

  } else {
    stop("one or more tests not recognised: un whichTests() for valid options.")
  }
}



